In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
np.random.seed(42)

n = 5000

workclass = [
"Private","Self-emp-not-inc","Self-emp-inc",
"Federal-gov","Local-gov","State-gov"
]

education = [
"Bachelors","Some-college","11th","HS-grad","Prof-school",
"Assoc-acdm","Assoc-voc","Masters","Doctorate"
]

marital_status = [
"Married-civ-spouse","Divorced","Never-married",
"Separated","Widowed","Married-spouse-absent"
]

occupation = [
"Tech-support","Craft-repair","Other-service","Sales",
"Exec-managerial","Prof-specialty","Adm-clerical"
]

relationship = [
"Wife","Own-child","Husband","Not-in-family","Unmarried"
]

race = [
"White","Asian-Pac-Islander","Amer-Indian-Eskimo",
"Other","Black"
]

sex = ["Female","Male"]

countries = [
"United-States","Germany","Canada","India",
"England","France","Mexico"
]

salary = ["<=50K",">50K"]

df = pd.DataFrame({

"age": np.random.randint(18,70,n),

"workclass": np.random.choice(workclass,n),

"fnlwgt": np.random.randint(10000,100000,n),

"education": np.random.choice(education,n),

"education-num": np.random.randint(1,16,n),

"marital-status": np.random.choice(marital_status,n),

"occupation": np.random.choice(occupation,n),

"relationship": np.random.choice(relationship,n),

"race": np.random.choice(race,n),

"sex": np.random.choice(sex,n),

"capital-gain": np.random.choice([0,0,0,0,5000,10000],n),

"capital-loss": np.random.choice([0,0,0,2000],n),

"hours-per-week": np.random.randint(20,60,n),

"native-country": np.random.choice(countries,n),

"salary": np.random.choice(salary,n)

})

df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,56,Private,73600,Assoc-acdm,11,Widowed,Other-service,Not-in-family,Asian-Pac-Islander,Male,10000,0,30,India,<=50K
1,69,Self-emp-not-inc,94981,Assoc-acdm,9,Widowed,Exec-managerial,Unmarried,Amer-Indian-Eskimo,Female,0,0,55,Mexico,<=50K
2,46,Federal-gov,81997,Bachelors,5,Divorced,Craft-repair,Not-in-family,Other,Male,5000,0,33,Mexico,>50K
3,32,Private,38205,Some-college,5,Never-married,Sales,Own-child,White,Female,10000,2000,54,Germany,<=50K
4,60,Local-gov,98887,HS-grad,9,Never-married,Prof-specialty,Not-in-family,Black,Male,5000,0,42,England,<=50K

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             5000 non-null   int64
 1   workclass       5000 non-null   str
 2   fnlwgt          5000 non-null   int64
 3   education       5000 non-null   str
 4   education-num   5000 non-null   int64
 5   marital-status  5000 non-null   str
 6   occupation      5000 non-null   str
 7   relationship    5000 non-null   str
 8   race            5000 non-null   str
 9   sex             5000 non-null   str
 10  capital-gain    5000 non-null   int64
 11  capital-loss    5000 non-null   int64
 12  hours-per-week  5000 non-null   int64
 13  native-country  5000 non-null   str
 14  salary          5000 non-null   str
dtypes: int64(6), str(9)
memory usage: 586.1 KB

In [6]:
df["sex"].value_counts()

sex
Male      2549
Female    2451
Name: count, dtype: int64

In [7]:
df[df["sex"] == "Female"]["age"].mean()

np.float64(43.605059159526725)

In [8]:
(df["native-country"] == "Germany").mean()

np.float64(0.1412)

In [9]:
df.groupby("salary")["age"].agg(["mean","std"])

             mean        std
salary
<=50K   43.843664  14.863572
>50K    43.318606  14.974235

In [10]:
higher_education = [
    "Bachelors","Prof-school","Assoc-acdm",
    "Assoc-voc","Masters","Doctorate"
]

df[df["salary"] == ">50K"]["education"].isin(higher_education).all()

np.False_

In [11]:
df.groupby(["race","sex"])["age"].describe()

                           count       mean        std   min   25%   50%  \
race               sex
Amer-Indian-Eskimo Female  482.0  43.489627  14.693433  18.0  31.0  43.0
                   Male    498.0  43.853414  14.791937  18.0  31.0  44.0
Asian-Pac-Islander Female  514.0  43.509728  15.200188  18.0  30.0  43.0
                   Male    525.0  44.177143  14.465445  18.0  33.0  44.0
Black              Female  466.0  43.736052  14.812414  18.0  31.0  44.0
                   Male    496.0  43.322581  14.968545  18.0  31.0  42.5
Other              Female  512.0  43.453125  15.292892  18.0  30.0  45.0
                   Male    507.0  43.078895  14.982127  18.0  30.0  43.0
White              Female  477.0  43.859539  15.028655  18.0  31.0  44.0
                   Male    523.0  43.376673  15.029396  18.0  30.0  43.0

                            75%   max
race               sex
Amer-Indian-Eskimo Female  56.0  69.0
                   Male    57.0  69.0
Asian-Pac-Islander Female  56.0  69.0
                   Male    56.0  69.0
Black              Female  56.0  69.0
                   Male    56.0  69.0
Other              Female  57.0  69.0
                   Male    56.0  69.0
White              Female  57.0  69.0
                   Male    56.0  69.0

In [12]:
df[(df["race"]=="Amer-Indian-Eskimo") & (df["sex"]=="Male")]["age"].max()

np.int64(69)

In [13]:
men = df[df["sex"] == "Male"]

married = men["marital-status"].str.startswith("Married")

men.groupby(married)["salary"].apply(lambda x: (x==">50K").mean())

marital-status
False    0.490544
True     0.494749
Name: salary, dtype: float64

In [14]:
max_hours = df["hours-per-week"].max()
max_hours

np.int64(59)

In [15]:
workers = df[df["hours-per-week"] == max_hours]
len(workers)

132

In [16]:
(workers["salary"] == ">50K").mean() * 100

np.float64(49.24242424242424)

In [17]:
df.groupby(["native-country","salary"])["hours-per-week"].mean()

native-country  salary
Canada          <=50K     39.295580
                >50K      40.304734
England         <=50K     40.067332
                >50K      39.502874
France          <=50K     39.587766
                >50K      39.054496
Germany         <=50K     39.124661
                >50K      39.780415
India           <=50K     38.327536
                >50K      38.677922
Mexico          <=50K     38.363905
                >50K      38.871642
United-States   <=50K     39.698830
                >50K      40.644258
Name: hours-per-week, dtype: float64

In [18]:
df["education"].value_counts().head(5)

education
Some-college    581
HS-grad         564
Masters         564
11th            560
Bachelors       558
Name: count, dtype: int64

In [19]:
education_salary = df.groupby("education")["salary"].apply(
    lambda x: (x==">50K").mean()
)

education_salary.sort_values(ascending=False).head(5)

education
11th            0.555357
Some-college    0.512909
Assoc-acdm      0.495396
Prof-school     0.493554
Masters         0.482270
Name: salary, dtype: float64

In [20]:
df[df["salary"]==">50K"]["occupation"].value_counts().head(5)

occupation
Exec-managerial    391
Tech-support       389
Sales              371
Adm-clerical       347
Other-service      340
Name: count, dtype: int64

In [21]:
df.groupby("salary")["hours-per-week"].mean()

salary
<=50K    39.234505
>50K     39.534657
Name: hours-per-week, dtype: float64

In [22]:
df.groupby("salary")["capital-gain"].apply(lambda x: (x>0).mean())

salary
<=50K    0.326885
>50K     0.334820
Name: capital-gain, dtype: float64

In [23]:
country_stats = df.groupby("native-country").agg(
    total=("salary","count"),
    high_income=("salary", lambda x: (x==">50K").sum())
)

country_stats = country_stats[country_stats["total"] >= 50]

country_stats["share"] = country_stats["high_income"] / country_stats["total"]

country_stats.sort_values("share", ascending=False).head(1)

                total  high_income     share
native-country
India             730          385  0.527397